//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace L_FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIN_domyluTDQvyRN_u_cF2FEA___0
    {
        public decimal USERINFO_ID { get; set; }
        public string USER_NAME { get; set; }
        public string PHONE { get; set; }
        public string ADDRESS { get; set; }
        public string MARJOR { get; set; }
        public string SEX { get; set; }
        public Nullable<System.DateTime> BIRTH { get; set; }
    }
}
