//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace L_FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_TAG
    {
        public decimal ID { get; set; }
        public decimal ITEM_ID { get; set; }
        public decimal TAG_ID { get; set; }
    
        public virtual ITEM ITEM { get; set; }
        public virtual TAG TAG { get; set; }
    }
}
