//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace L_FMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LFMSContext : DbContext
    {
        public LFMSContext()
            : base("name=LFMSContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACCOUNT> ACCOUNT { get; set; }
        public DbSet<BIN__wgguIj2TRe65DYjmKQxBQ___0> BIN__wgguIj2TRe65DYjmKQxBQ___0 { get; set; }
        public DbSet<BIN_18b4Ab25Thek4_jpb2K7aw___0> BIN_18b4Ab25Thek4_jpb2K7aw___0 { get; set; }
        public DbSet<BIN_FIgeY_AxRPCsTVceq3DXdg___0> BIN_FIgeY_AxRPCsTVceq3DXdg___0 { get; set; }
        public DbSet<BIN_IgTcN3GVQNaMJ23ARcpWTQ___0> BIN_IgTcN3GVQNaMJ23ARcpWTQ___0 { get; set; }
        public DbSet<BIN_lsbfHaLCT_WVCJKh3se8bA___0> BIN_lsbfHaLCT_WVCJKh3se8bA___0 { get; set; }
        public DbSet<BIN_lY20SNslRj6z000EApIGVA___0> BIN_lY20SNslRj6z000EApIGVA___0 { get; set; }
        public DbSet<BIN_OivbSlE0S_6tPK0LyXVhVg___0> BIN_OivbSlE0S_6tPK0LyXVhVg___0 { get; set; }
        public DbSet<BIN_Om0g3q92QreGP79JqJv3Dw___0> BIN_Om0g3q92QreGP79JqJv3Dw___0 { get; set; }
        public DbSet<BIN_qEa__YpBSkGOXv6CIGLNfw___0> BIN_qEa__YpBSkGOXv6CIGLNfw___0 { get; set; }
        public DbSet<BIN_t0_yFBTzRxKHMtcZDz2y4A___0> BIN_t0_yFBTzRxKHMtcZDz2y4A___0 { get; set; }
        public DbSet<BIN_TUA0jZntQmSciz0N0b_oug___0> BIN_TUA0jZntQmSciz0N0b_oug___0 { get; set; }
        public DbSet<BIN_x3lFD8scRfuJ344Fh5RmLw___0> BIN_x3lFD8scRfuJ344Fh5RmLw___0 { get; set; }
        public DbSet<BIN_xPSz9jBzSvGFuzr1e10E_g___0> BIN_xPSz9jBzSvGFuzr1e10E_g___0 { get; set; }
        public DbSet<BIN_zcz8r0VsStKzEIx4TwtFrg___0> BIN_zcz8r0VsStKzEIx4TwtFrg___0 { get; set; }
        public DbSet<COMMENTS> COMMENTS { get; set; }
        public DbSet<DIALOG> DIALOG { get; set; }
        public DbSet<ITEM> ITEM { get; set; }
        public DbSet<MESSAGE> MESSAGE { get; set; }
        public DbSet<QUESTION> QUESTION { get; set; }
        public DbSet<TAG> TAG { get; set; }
        public DbSet<USER_INFO> USER_INFO { get; set; }
        public DbSet<BIN__Pi9y47aSG2mtY7QlBbTsQ___0> BIN__Pi9y47aSG2mtY7QlBbTsQ___0 { get; set; }
        public DbSet<BIN_A2KczbINR2iLELtfj1oM7Q___0> BIN_A2KczbINR2iLELtfj1oM7Q___0 { get; set; }
        public DbSet<BIN_CSzfDaJzTiO50j1oswq5gA___0> BIN_CSzfDaJzTiO50j1oswq5gA___0 { get; set; }
        public DbSet<BIN_dXHv22TuTQqUadd_Hnf_KA___0> BIN_dXHv22TuTQqUadd_Hnf_KA___0 { get; set; }
        public DbSet<BIN_ntbFFai1QNCb3Ibm3DjVcg___0> BIN_ntbFFai1QNCb3Ibm3DjVcg___0 { get; set; }
        public DbSet<BIN_OEy1Sfw4QM6iJVTS7yc9_A___0> BIN_OEy1Sfw4QM6iJVTS7yc9_A___0 { get; set; }
        public DbSet<BIN_PDRzAj9hSy6uzDY68Pe2xw___0> BIN_PDRzAj9hSy6uzDY68Pe2xw___0 { get; set; }
        public DbSet<BIN_Q9xlsPxVRDWQS5BehDuepw___0> BIN_Q9xlsPxVRDWQS5BehDuepw___0 { get; set; }
        public DbSet<BIN_QT_90KmGQ3mjajf5AVdmCA___0> BIN_QT_90KmGQ3mjajf5AVdmCA___0 { get; set; }
        public DbSet<BIN_S1SbY_HURbWuE_KiDkBjPA___0> BIN_S1SbY_HURbWuE_KiDkBjPA___0 { get; set; }
        public DbSet<BIN_VNFqbGBSRNK0xpOGRkKTrQ___0> BIN_VNFqbGBSRNK0xpOGRkKTrQ___0 { get; set; }
        public DbSet<BIN_Y_RUNdYfQLKwdhXEf0rDEw___0> BIN_Y_RUNdYfQLKwdhXEf0rDEw___0 { get; set; }
        public DbSet<COMMENT_ITEM_USER> COMMENT_ITEM_USER { get; set; }
        public DbSet<PUBLISHMENT> PUBLISHMENT { get; set; }
    }
}
