//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace L_FMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LFMSContext : DbContext
    {
        public LFMSContext()
            : base("name=LFMSContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACCOUNT> ACCOUNT { get; set; }
        public DbSet<COMMENT_ITEM_USER> COMMENT_ITEM_USER { get; set; }
        public DbSet<COMMENTS> COMMENTS { get; set; }
        public DbSet<DIALOG> DIALOG { get; set; }
        public DbSet<DIALOG_MESSAGE> DIALOG_MESSAGE { get; set; }
        public DbSet<ITEM> ITEM { get; set; }
        public DbSet<ITEM_TAG> ITEM_TAG { get; set; }
        public DbSet<MESSAGE> MESSAGE { get; set; }
        public DbSet<PUBLISHMENT> PUBLISHMENT { get; set; }
        public DbSet<QUESTION> QUESTION { get; set; }
        public DbSet<TAG> TAG { get; set; }
        public DbSet<USER_QUESTION> USER_QUESTION { get; set; }
        public DbSet<USER_USERINFO> USER_USERINFO { get; set; }
        public DbSet<USERINFO> USERINFO { get; set; }
    }
}
