//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace L_FMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LFMSContext : DbContext
    {
        public LFMSContext()
            : base("name=LFMSContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACCOUNT> ACCOUNT { get; set; }
        public DbSet<BIN__oSXYPjIRae7JsdHZM6Gfg___0> BIN__oSXYPjIRae7JsdHZM6Gfg___0 { get; set; }
        public DbSet<BIN_2gWi6y0hRgqCCljH9bNgcg___0> BIN_2gWi6y0hRgqCCljH9bNgcg___0 { get; set; }
        public DbSet<BIN_3XLgZX1HT7GwQOROPCtTsg___0> BIN_3XLgZX1HT7GwQOROPCtTsg___0 { get; set; }
        public DbSet<BIN_gk9HRXiZTfSg9MJAgQ_RPA___0> BIN_gk9HRXiZTfSg9MJAgQ_RPA___0 { get; set; }
        public DbSet<BIN_hWsQqvkbRXisEv_ei01Oug___0> BIN_hWsQqvkbRXisEv_ei01Oug___0 { get; set; }
        public DbSet<BIN_jt3GW_4VQJO_Yd7kT_3oPQ___0> BIN_jt3GW_4VQJO_Yd7kT_3oPQ___0 { get; set; }
        public DbSet<BIN_KZ9Bu1aLQ2G25d5Ao6QoaA___0> BIN_KZ9Bu1aLQ2G25d5Ao6QoaA___0 { get; set; }
        public DbSet<BIN_pE3dwcRjQTGoqKLda3ok7A___0> BIN_pE3dwcRjQTGoqKLda3ok7A___0 { get; set; }
        public DbSet<BIN_RazsQK9sQmyZ1z6g9QjXOw___0> BIN_RazsQK9sQmyZ1z6g9QjXOw___0 { get; set; }
        public DbSet<BIN_rVSaJnSQTM69NulG53LS5g___0> BIN_rVSaJnSQTM69NulG53LS5g___0 { get; set; }
        public DbSet<BIN_RynuPJj7T8_Rc1KsGZi_wQ___0> BIN_RynuPJj7T8_Rc1KsGZi_wQ___0 { get; set; }
        public DbSet<BIN_sBhNt8z4Tt6lGurZa5Xhrg___0> BIN_sBhNt8z4Tt6lGurZa5Xhrg___0 { get; set; }
        public DbSet<BIN_vbTPm9zLQriiKf3H4UWsdg___0> BIN_vbTPm9zLQriiKf3H4UWsdg___0 { get; set; }
        public DbSet<BIN_xqzNPCh0SZ2B_m5N2VmIVQ___0> BIN_xqzNPCh0SZ2B_m5N2VmIVQ___0 { get; set; }
        public DbSet<COMMENTS> COMMENTS { get; set; }
        public DbSet<DIALOG> DIALOG { get; set; }
        public DbSet<ITEM> ITEM { get; set; }
        public DbSet<MESSAGE> MESSAGE { get; set; }
        public DbSet<QUESTION> QUESTION { get; set; }
        public DbSet<TAG> TAG { get; set; }
        public DbSet<BIN__7MAdHv7TimSm15EhbbwWQ___0> BIN__7MAdHv7TimSm15EhbbwWQ___0 { get; set; }
        public DbSet<BIN_2yz8ZhlYSiGZ_9Qpzbkjsw___0> BIN_2yz8ZhlYSiGZ_9Qpzbkjsw___0 { get; set; }
        public DbSet<BIN_4RbnMKYTTJyytLkhCLbEmA___0> BIN_4RbnMKYTTJyytLkhCLbEmA___0 { get; set; }
        public DbSet<BIN_BrG5SzvDTjqR5_7Q0GY9cQ___0> BIN_BrG5SzvDTjqR5_7Q0GY9cQ___0 { get; set; }
        public DbSet<BIN_D6umIElOTKqEtHE0JAfROA___0> BIN_D6umIElOTKqEtHE0JAfROA___0 { get; set; }
        public DbSet<BIN_DNN7Xt2gSjGXF4pVEWQ2kg___0> BIN_DNN7Xt2gSjGXF4pVEWQ2kg___0 { get; set; }
        public DbSet<BIN_fT9zzFPoQZmrxcpT1HvnTw___0> BIN_fT9zzFPoQZmrxcpT1HvnTw___0 { get; set; }
        public DbSet<BIN_H3SpbV9JTSqjo5ey03pwgw___0> BIN_H3SpbV9JTSqjo5ey03pwgw___0 { get; set; }
        public DbSet<BIN_kqKvNg3YQFGQUsPZz_MEeQ___0> BIN_kqKvNg3YQFGQUsPZz_MEeQ___0 { get; set; }
        public DbSet<BIN_t190R_f3Q_e0yuy44iFSUg___0> BIN_t190R_f3Q_e0yuy44iFSUg___0 { get; set; }
        public DbSet<BIN_WsJrS2mfTmOXAp_JdzAJBQ___0> BIN_WsJrS2mfTmOXAp_JdzAJBQ___0 { get; set; }
        public DbSet<BIN_wW2ep4vGRiak7EIzyyBgOA___0> BIN_wW2ep4vGRiak7EIzyyBgOA___0 { get; set; }
        public DbSet<BIN_YhoaRZuvRiKnLfV63aVjRQ___0> BIN_YhoaRZuvRiKnLfV63aVjRQ___0 { get; set; }
        public DbSet<COMMENT_ITEM_USER> COMMENT_ITEM_USER { get; set; }
        public DbSet<PUBLISHMENT> PUBLISHMENT { get; set; }
        public DbSet<USER_INFO> USER_INFO { get; set; }
        public DbSet<BIN_6zOSJQSJRfOyTAAhplrjCw___0> BIN_6zOSJQSJRfOyTAAhplrjCw___0 { get; set; }
        public DbSet<BIN_80Zz_0AMQnWEbHQLkXPjSQ___0> BIN_80Zz_0AMQnWEbHQLkXPjSQ___0 { get; set; }
        public DbSet<BIN_ayUilLN3QnaUrTGigo_Ukg___0> BIN_ayUilLN3QnaUrTGigo_Ukg___0 { get; set; }
        public DbSet<BIN_BNVsv3G7S2muiJox_SUkcQ___0> BIN_BNVsv3G7S2muiJox_SUkcQ___0 { get; set; }
        public DbSet<BIN_by_PKehCQLS7B8lSqQd2tA___0> BIN_by_PKehCQLS7B8lSqQd2tA___0 { get; set; }
        public DbSet<BIN_cwQBVjbARl2XPx069aa8PQ___0> BIN_cwQBVjbARl2XPx069aa8PQ___0 { get; set; }
        public DbSet<BIN_diLIuTV_SW24gcvJK_LOgQ___0> BIN_diLIuTV_SW24gcvJK_LOgQ___0 { get; set; }
        public DbSet<BIN_E3_Bmw9oTcWxVMTNT7Hd4A___0> BIN_E3_Bmw9oTcWxVMTNT7Hd4A___0 { get; set; }
        public DbSet<BIN_hLg0w5nzSoGFnXsj5pniLg___0> BIN_hLg0w5nzSoGFnXsj5pniLg___0 { get; set; }
        public DbSet<BIN_P_HWsE9pSzSXrXKx_qL5Eg___0> BIN_P_HWsE9pSzSXrXKx_qL5Eg___0 { get; set; }
        public DbSet<BIN_1GYcU5LmSXaTLgbJTvWaXg___0> BIN_1GYcU5LmSXaTLgbJTvWaXg___0 { get; set; }
        public DbSet<BIN_7SSOED8PQUWtrB0fj2YkEA___0> BIN_7SSOED8PQUWtrB0fj2YkEA___0 { get; set; }
        public DbSet<BIN_9AHObWhlTcuiU7NRMQne2A___0> BIN_9AHObWhlTcuiU7NRMQne2A___0 { get; set; }
        public DbSet<BIN_Eu88QouwRqeNHf4taFOGyw___0> BIN_Eu88QouwRqeNHf4taFOGyw___0 { get; set; }
        public DbSet<BIN_GHu6buV9Tg_mIZQwlzTiTw___0> BIN_GHu6buV9Tg_mIZQwlzTiTw___0 { get; set; }
        public DbSet<BIN_kzKEqsuxQKmGb1UziV9gfg___0> BIN_kzKEqsuxQKmGb1UziV9gfg___0 { get; set; }
        public DbSet<BIN_tgkLxY9STLKLb375K1qCrQ___0> BIN_tgkLxY9STLKLb375K1qCrQ___0 { get; set; }
        public DbSet<BIN_ww7NyT50Tfermhk8ewCiKg___0> BIN_ww7NyT50Tfermhk8ewCiKg___0 { get; set; }
        public DbSet<BIN_ZalIcyrpQfaQn0FVeyGp_Q___0> BIN_ZalIcyrpQfaQn0FVeyGp_Q___0 { get; set; }
        public DbSet<BIN_zn82Buo4Rqe1sOx2_6QSLw___0> BIN_zn82Buo4Rqe1sOx2_6QSLw___0 { get; set; }
        public DbSet<BIN__S65GmV2S_K0BYBurAlNnA___0> BIN__S65GmV2S_K0BYBurAlNnA___0 { get; set; }
        public DbSet<BIN_4qngejeaRoC_6YN7ODVgNQ___0> BIN_4qngejeaRoC_6YN7ODVgNQ___0 { get; set; }
        public DbSet<BIN_A_4ZVx5URyyzWFqdyirkqA___0> BIN_A_4ZVx5URyyzWFqdyirkqA___0 { get; set; }
        public DbSet<BIN_ErZ2Uk58RL6nd3M_m0sZjA___0> BIN_ErZ2Uk58RL6nd3M_m0sZjA___0 { get; set; }
        public DbSet<BIN_N6YOj3e8RlKk48pcQoBHHg___0> BIN_N6YOj3e8RlKk48pcQoBHHg___0 { get; set; }
        public DbSet<BIN_ogeySXeDT8eY6Vwo9gUkgg___0> BIN_ogeySXeDT8eY6Vwo9gUkgg___0 { get; set; }
        public DbSet<BIN_XqRl5vUQTgyqY8644kGLwg___0> BIN_XqRl5vUQTgyqY8644kGLwg___0 { get; set; }
        public DbSet<BIN_3LkFiLLLRk2_N1VV_ZulQw___0> BIN_3LkFiLLLRk2_N1VV_ZulQw___0 { get; set; }
        public DbSet<BIN_bBoZwa_TTUmtoKuzB8NhOw___0> BIN_bBoZwa_TTUmtoKuzB8NhOw___0 { get; set; }
        public DbSet<BIN_NFVpiXvUSr6pQIwEYn3weA___0> BIN_NFVpiXvUSr6pQIwEYn3weA___0 { get; set; }
        public DbSet<BIN_PiD1ZzYSQt_3DioJGEYD5g___0> BIN_PiD1ZzYSQt_3DioJGEYD5g___0 { get; set; }
        public DbSet<BIN_xlW2gfT5S6OtEVO651ItVw___0> BIN_xlW2gfT5S6OtEVO651ItVw___0 { get; set; }
        public DbSet<BIN_YlkkJHBWTjmHN8nJdHlptw___0> BIN_YlkkJHBWTjmHN8nJdHlptw___0 { get; set; }
    }
}
