//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace L_FMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LFMSContext : DbContext
    {
        public LFMSContext()
            : base("name=LFMSContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACCOUNT> ACCOUNT { get; set; }
        public DbSet<BIN__oSXYPjIRae7JsdHZM6Gfg___0> BIN__oSXYPjIRae7JsdHZM6Gfg___0 { get; set; }
        public DbSet<BIN_2gWi6y0hRgqCCljH9bNgcg___0> BIN_2gWi6y0hRgqCCljH9bNgcg___0 { get; set; }
        public DbSet<BIN_3XLgZX1HT7GwQOROPCtTsg___0> BIN_3XLgZX1HT7GwQOROPCtTsg___0 { get; set; }
        public DbSet<BIN_gk9HRXiZTfSg9MJAgQ_RPA___0> BIN_gk9HRXiZTfSg9MJAgQ_RPA___0 { get; set; }
        public DbSet<BIN_hWsQqvkbRXisEv_ei01Oug___0> BIN_hWsQqvkbRXisEv_ei01Oug___0 { get; set; }
        public DbSet<BIN_jt3GW_4VQJO_Yd7kT_3oPQ___0> BIN_jt3GW_4VQJO_Yd7kT_3oPQ___0 { get; set; }
        public DbSet<BIN_KZ9Bu1aLQ2G25d5Ao6QoaA___0> BIN_KZ9Bu1aLQ2G25d5Ao6QoaA___0 { get; set; }
        public DbSet<BIN_pE3dwcRjQTGoqKLda3ok7A___0> BIN_pE3dwcRjQTGoqKLda3ok7A___0 { get; set; }
        public DbSet<BIN_RazsQK9sQmyZ1z6g9QjXOw___0> BIN_RazsQK9sQmyZ1z6g9QjXOw___0 { get; set; }
        public DbSet<BIN_rVSaJnSQTM69NulG53LS5g___0> BIN_rVSaJnSQTM69NulG53LS5g___0 { get; set; }
        public DbSet<BIN_RynuPJj7T8_Rc1KsGZi_wQ___0> BIN_RynuPJj7T8_Rc1KsGZi_wQ___0 { get; set; }
        public DbSet<BIN_sBhNt8z4Tt6lGurZa5Xhrg___0> BIN_sBhNt8z4Tt6lGurZa5Xhrg___0 { get; set; }
        public DbSet<BIN_vbTPm9zLQriiKf3H4UWsdg___0> BIN_vbTPm9zLQriiKf3H4UWsdg___0 { get; set; }
        public DbSet<BIN_xqzNPCh0SZ2B_m5N2VmIVQ___0> BIN_xqzNPCh0SZ2B_m5N2VmIVQ___0 { get; set; }
        public DbSet<COMMENTS> COMMENTS { get; set; }
        public DbSet<DIALOG> DIALOG { get; set; }
        public DbSet<ITEM> ITEM { get; set; }
        public DbSet<MESSAGE> MESSAGE { get; set; }
        public DbSet<QUESTION> QUESTION { get; set; }
        public DbSet<TAG> TAG { get; set; }
        public DbSet<BIN__7MAdHv7TimSm15EhbbwWQ___0> BIN__7MAdHv7TimSm15EhbbwWQ___0 { get; set; }
        public DbSet<BIN_2yz8ZhlYSiGZ_9Qpzbkjsw___0> BIN_2yz8ZhlYSiGZ_9Qpzbkjsw___0 { get; set; }
        public DbSet<BIN_4RbnMKYTTJyytLkhCLbEmA___0> BIN_4RbnMKYTTJyytLkhCLbEmA___0 { get; set; }
        public DbSet<BIN_BrG5SzvDTjqR5_7Q0GY9cQ___0> BIN_BrG5SzvDTjqR5_7Q0GY9cQ___0 { get; set; }
        public DbSet<BIN_D6umIElOTKqEtHE0JAfROA___0> BIN_D6umIElOTKqEtHE0JAfROA___0 { get; set; }
        public DbSet<BIN_DNN7Xt2gSjGXF4pVEWQ2kg___0> BIN_DNN7Xt2gSjGXF4pVEWQ2kg___0 { get; set; }
        public DbSet<BIN_fT9zzFPoQZmrxcpT1HvnTw___0> BIN_fT9zzFPoQZmrxcpT1HvnTw___0 { get; set; }
        public DbSet<BIN_H3SpbV9JTSqjo5ey03pwgw___0> BIN_H3SpbV9JTSqjo5ey03pwgw___0 { get; set; }
        public DbSet<BIN_kqKvNg3YQFGQUsPZz_MEeQ___0> BIN_kqKvNg3YQFGQUsPZz_MEeQ___0 { get; set; }
        public DbSet<BIN_t190R_f3Q_e0yuy44iFSUg___0> BIN_t190R_f3Q_e0yuy44iFSUg___0 { get; set; }
        public DbSet<BIN_WsJrS2mfTmOXAp_JdzAJBQ___0> BIN_WsJrS2mfTmOXAp_JdzAJBQ___0 { get; set; }
        public DbSet<BIN_wW2ep4vGRiak7EIzyyBgOA___0> BIN_wW2ep4vGRiak7EIzyyBgOA___0 { get; set; }
        public DbSet<BIN_YhoaRZuvRiKnLfV63aVjRQ___0> BIN_YhoaRZuvRiKnLfV63aVjRQ___0 { get; set; }
        public DbSet<COMMENT_ITEM_USER> COMMENT_ITEM_USER { get; set; }
        public DbSet<PUBLISHMENT> PUBLISHMENT { get; set; }
        public DbSet<USER_INFO> USER_INFO { get; set; }
    }
}
